-- CreateTable
CREATE TABLE "statistics" (
    "idx" SERIAL NOT NULL,
    "name" TEXT NOT NULL,
    "ZvsZ_W" INTEGER NOT NULL DEFAULT 0,
    "ZvsZ_L" INTEGER NOT NULL DEFAULT 0,
    "ZvsT_W" INTEGER NOT NULL DEFAULT 0,
    "ZvsT_L" INTEGER NOT NULL DEFAULT 0,
    "ZvsP_W" INTEGER NOT NULL DEFAULT 0,
    "ZvsP_L" INTEGER NOT NULL DEFAULT 0,
    "TvsZ_W" INTEGER NOT NULL DEFAULT 0,
    "TvsZ_L" INTEGER NOT NULL DEFAULT 0,
    "TvsT_W" INTEGER NOT NULL DEFAULT 0,
    "TvsT_L" INTEGER NOT NULL DEFAULT 0,
    "TvsP_W" INTEGER NOT NULL DEFAULT 0,
    "TvsP_L" INTEGER NOT NULL DEFAULT 0,
    "PvsZ_W" INTEGER NOT NULL DEFAULT 0,
    "PvsZ_L" INTEGER NOT NULL DEFAULT 0,
    "PvsT_W" INTEGER NOT NULL DEFAULT 0,
    "PvsT_L" INTEGER NOT NULL DEFAULT 0,
    "PvsP_W" INTEGER NOT NULL DEFAULT 0,
    "PvsP_L" INTEGER NOT NULL DEFAULT 0,

    CONSTRAINT "statistics_pkey" PRIMARY KEY ("idx")
);

-- CreateIndex
CREATE UNIQUE INDEX "statistics_name_key" ON "statistics"("name");
